/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AgeVerifyFailureCode
 */
public class AgeVerifyFailureCodeTest {
    /**
     * Model tests for AgeVerifyFailureCode
     */
    @Test
    public void testAgeVerifyFailureCode() {
        // TODO: test AgeVerifyFailureCode
    }

}
