/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AgeVerifyResult
 */
public class AgeVerifyResultTest {
    private final AgeVerifyResult model = new AgeVerifyResult();

    /**
     * Model tests for AgeVerifyResult
     */
    @Test
    public void testAgeVerifyResult() {
        // TODO: test AgeVerifyResult
    }

    /**
     * Test the property 'isOfAge'
     */
    @Test
    public void isOfAgeTest() {
        // TODO: test isOfAge
    }

    /**
     * Test the property 'failureCodes'
     */
    @Test
    public void failureCodesTest() {
        // TODO: test failureCodes
    }

}
