/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ShippingVerifyResultLines;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ShippingVerifyResult
 */
public class ShippingVerifyResultTest {
    private final ShippingVerifyResult model = new ShippingVerifyResult();

    /**
     * Model tests for ShippingVerifyResult
     */
    @Test
    public void testShippingVerifyResult() {
        // TODO: test ShippingVerifyResult
    }

    /**
     * Test the property 'compliant'
     */
    @Test
    public void compliantTest() {
        // TODO: test compliant
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'successMessages'
     */
    @Test
    public void successMessagesTest() {
        // TODO: test successMessages
    }

    /**
     * Test the property 'failureMessages'
     */
    @Test
    public void failureMessagesTest() {
        // TODO: test failureMessages
    }

    /**
     * Test the property 'failureCodes'
     */
    @Test
    public void failureCodesTest() {
        // TODO: test failureCodes
    }

    /**
     * Test the property 'warningCodes'
     */
    @Test
    public void warningCodesTest() {
        // TODO: test warningCodes
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

}
