/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AgeVerifyFailureCode
 */
@JsonAdapter(AgeVerifyFailureCode.Adapter.class)
public enum AgeVerifyFailureCode {
  
  NOT_FOUND("not_found"),
  
  DOB_UNVERIFIABLE("dob_unverifiable"),
  
  UNDER_AGE("under_age"),
  
  SUSPECTED_FRAUD("suspected_fraud"),
  
  DECEASED("deceased"),
  
  UNKNOWN_ERROR("unknown_error");

  private String value;

  AgeVerifyFailureCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AgeVerifyFailureCode fromValue(String value) {
    for (AgeVerifyFailureCode b : AgeVerifyFailureCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AgeVerifyFailureCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final AgeVerifyFailureCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AgeVerifyFailureCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AgeVerifyFailureCode.fromValue(value);
    }
  }
}

