/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import Avalara.SDK.ApiClient;
import Avalara.SDK.ApiException;
import Avalara.SDK.Configuration;
import Avalara.SDK.AvaTaxEnvironment;
import org.openapitools.client.model.AgeVerifyFailureCode;
import org.openapitools.client.model.AgeVerifyRequest;
import org.openapitools.client.model.AgeVerifyResult;
import org.junit.Test;
import org.junit.Ignore;

import org.openapitools.client.model.AgeVerifyRequestAddress;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgeVerificationApi
 */
@Ignore
public class AgeVerificationApiTest {
    private AgeVerificationApi api;

    public AgeVerificationApiTest() {
        Configuration configuration = new Configuration();
        configuration.setAppName("Test");
        configuration.setAppVersion("1.0");
        configuration.setMachineName("LocalBox");
        // Configure Auth to run test here.
        configuration.setUsername("foo");
        configuration.setPassword("bar");
        configuration.setTimeout(5000);
        configuration.setEnvironment(AvaTaxEnvironment.Sandbox);
        ApiClient apiClient = new ApiClient(configuration);
        api = new AgeVerificationApi(apiClient);
    }
    /**
     * Determines whether an individual meets or exceeds the minimum legal drinking age.
     *
     * The request must meet the following criteria in order to be evaluated: * *firstName*, *lastName*, and *address* are required fields. * One of the following sets of attributes are required for the *address*:   * *line1, city, region*   * *line1, postalCode*  Optionally, the transaction and its lines may use the following parameters: * A *DOB* (Date of Birth) field. The value should be ISO-8601 compliant (e.g. 2020-07-21). * Beyond the required *address* fields above, a *country* field is permitted   * The valid values for this attribute are [*US, USA*]  **Security Policies** This API depends on the active subscription *AgeVerification*
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyAgeTest() throws ApiException {
        AgeVerifyRequest request = new AgeVerifyRequest();
        request.firstName("Test");
        request.lastName("Person");
        AgeVerifyRequestAddress address = new AgeVerifyRequestAddress();
        address.line1("255 S King St");
        address.postalCode("98109");
        request.address(address);
        request.setDOB("1970-01-01");
        AgeVerifyResult response = api.verifyAge(request, null);
        // TODO: test validations
    }
    
}
