/*
 * Avalara Shipping Verification only
 * API for evaluating transactions against direct-to-consumer Beverage Alcohol shipping regulations.  This API is currently in beta. 
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import Avalara.SDK.ApiClient;
import Avalara.SDK.ApiException;
import Avalara.SDK.Configuration;
import org.openapitools.client.model.ErrorDetails;
import org.openapitools.client.model.ShippingVerifyResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShippingVerificationApi
 */
@Ignore
public class ShippingVerificationApiTest {
    // TODO: How do we setup the configuration object
    private Configuration configuration = new Configuration();
    private ApiClient apiClient = new ApiClient(configuration);
    private final ShippingVerificationApi api = new ShippingVerificationApi(apiClient);

    /**
     * Removes the transaction from consideration when evaluating regulations that span multiple transactions.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deregisterShipmentTest() throws ApiException {
        String companyCode = null;
        String transactionCode = null;
        String documentType = null;
                api.deregisterShipment(companyCode, transactionCode, documentType);
        // TODO: test validations
    }
    
    /**
     * Registers the transaction so that it may be included when evaluating regulations that span multiple transactions.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerShipmentTest() throws ApiException {
        String companyCode = null;
        String transactionCode = null;
        String documentType = null;
                api.registerShipment(companyCode, transactionCode, documentType);
        // TODO: test validations
    }
    
    /**
     * Evaluates a transaction against a set of direct-to-consumer shipping regulations and, if compliant, registers the transaction so that it may be included when evaluating regulations that span multiple transactions.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerShipmentIfCompliantTest() throws ApiException {
        String companyCode = null;
        String transactionCode = null;
        String documentType = null;
                ShippingVerifyResult response = api.registerShipmentIfCompliant(companyCode, transactionCode, documentType);
        // TODO: test validations
    }
    
    /**
     * Evaluates a transaction against a set of direct-to-consumer shipping regulations.
     *
     * The transaction and its lines must meet the following criteria in order to be evaluated: * The transaction must be recorded. Using a type of *SalesInvoice* is recommended. * A parameter with the name *AlcoholRouteType* must be specified and the value must be one of the following: &#39;*DTC*&#39;, &#39;*Retailer DTC*&#39; * A parameter with the name *RecipientName* must be specified and the value must be the name of the recipient. * Each alcohol line must include a *ContainerSize* parameter that describes the volume of a single container. Use the *unit* field to specify one of the following units: &#39;*Litre*&#39;, &#39;*Millilitre*&#39;, &#39;*gallon (US fluid)*&#39;, &#39;*quart (US fluid)*&#39;, &#39;*ounce (fluid US customary)*&#39; * Each alcohol line must include a *PackSize* parameter that describes the number of containers in a pack. Specify *Count* in the *unit* field.  Optionally, the transaction and its lines may use the following parameters: * The *ShipDate* parameter may be used if the date of shipment is different than the date of the transaction. The value should be ISO-8601 compliant (e.g. 2020-07-21). * The *RecipientDOB* parameter may be used to evaluate age restrictions. The value should be ISO-8601 compliant (e.g. 2020-07-21). * The *PurchaserDOB* parameter may be used to evaluate age restrictions. The value should be ISO-8601 compliant (e.g. 2020-07-21). * The *SalesLocation* parameter may be used to describe whether the sale was made *OnSite* or *OffSite*. *OffSite* is the default value. * The *AlcoholContent* parameter may be used to describe the alcohol percentage by volume of the item. Specify *Percentage* in the *unit* field.  **Security Policies** This API depends on all of the following active subscriptions: *AvaAlcohol, AutoAddress, AvaTaxPro*
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyShipmentTest() throws ApiException {
        String companyCode = null;
        String transactionCode = null;
        String documentType = null;
                ShippingVerifyResult response = api.verifyShipment(companyCode, transactionCode, documentType);
        // TODO: test validations
    }
    
}
